# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'steemwaller.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_steem(object):
    def setupUi(self, steem):
        steem.setObjectName("steem")
        steem.resize(863, 832)
        self.centralwidget = QtWidgets.QWidget(steem)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(220, 190, 621, 431))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(10, 40, 151, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.Button_trans = QtWidgets.QPushButton(self.tab)
        self.Button_trans.setGeometry(QtCore.QRect(150, 350, 75, 23))
        self.Button_trans.setObjectName("Button_trans")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(280, 240, 321, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.steem_to_sbd = QtWidgets.QLineEdit(self.layoutWidget)
        self.steem_to_sbd.setObjectName("steem_to_sbd")
        self.verticalLayout_3.addWidget(self.steem_to_sbd)
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(280, 220, 151, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(280, 40, 151, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(450, 80, 141, 61))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.power_down = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.power_down.setObjectName("power_down")
        self.horizontalLayout_6.addWidget(self.power_down)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(280, 80, 141, 61))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_14 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_4.addWidget(self.label_14)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.power_up = QtWidgets.QLineEdit(self.widget)
        self.power_up.setObjectName("power_up")
        self.horizontalLayout_3.addWidget(self.power_up)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.widget1 = QtWidgets.QWidget(self.tab)
        self.widget1.setGeometry(QtCore.QRect(340, 310, 201, 56))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Button_to_steem = QtWidgets.QPushButton(self.widget1)
        self.Button_to_steem.setObjectName("Button_to_steem")
        self.horizontalLayout_2.addWidget(self.Button_to_steem)
        self.Button_to_sbd = QtWidgets.QPushButton(self.widget1)
        self.Button_to_sbd.setObjectName("Button_to_sbd")
        self.horizontalLayout_2.addWidget(self.Button_to_sbd)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.Button_cancer = QtWidgets.QPushButton(self.widget1)
        self.Button_cancer.setObjectName("Button_cancer")
        self.verticalLayout_4.addWidget(self.Button_cancer)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(300, 210, 291, 5))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(280, 60, 331, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.widget2 = QtWidgets.QWidget(self.tab)
        self.widget2.setGeometry(QtCore.QRect(10, 80, 212, 261))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.trans_to = QtWidgets.QLineEdit(self.widget2)
        self.trans_to.setObjectName("trans_to")
        self.verticalLayout_2.addWidget(self.trans_to)
        self.label_10 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.trans_token = QtWidgets.QLineEdit(self.widget2)
        self.trans_token.setObjectName("trans_token")
        self.verticalLayout_2.addWidget(self.trans_token)
        self.label_11 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.trans_num = QtWidgets.QLineEdit(self.widget2)
        self.trans_num.setObjectName("trans_num")
        self.verticalLayout_2.addWidget(self.trans_num)
        self.label_12 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.trans_memo = QtWidgets.QLineEdit(self.widget2)
        self.trans_memo.setObjectName("trans_memo")
        self.verticalLayout_2.addWidget(self.trans_memo)
        self.widget3 = QtWidgets.QWidget(self.tab)
        self.widget3.setGeometry(QtCore.QRect(290, 150, 281, 54))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Button_power = QtWidgets.QPushButton(self.widget3)
        self.Button_power.setObjectName("Button_power")
        self.verticalLayout_7.addWidget(self.Button_power)
        self.Button_cancer_power = QtWidgets.QPushButton(self.widget3)
        self.Button_cancer_power.setObjectName("Button_cancer_power")
        self.verticalLayout_7.addWidget(self.Button_cancer_power)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.daili_to = QtWidgets.QLineEdit(self.tab_2)
        self.daili_to.setGeometry(QtCore.QRect(110, 70, 371, 41))
        self.daili_to.setObjectName("daili_to")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(110, 45, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(110, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.Button_daili = QtWidgets.QPushButton(self.tab_2)
        self.Button_daili.setGeometry(QtCore.QRect(110, 190, 371, 31))
        self.Button_daili.setObjectName("Button_daili")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(110, 115, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.daili_num = QtWidgets.QLineEdit(self.tab_2)
        self.daili_num.setGeometry(QtCore.QRect(110, 140, 371, 41))
        self.daili_num.setObjectName("daili_num")
        self.Button_daili_cancer = QtWidgets.QPushButton(self.tab_2)
        self.Button_daili_cancer.setGeometry(QtCore.QRect(110, 230, 371, 31))
        self.Button_daili_cancer.setObjectName("Button_daili_cancer")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(110, 290, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(110, 320, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.daili_to_who = QtWidgets.QLineEdit(self.tab_2)
        self.daili_to_who.setGeometry(QtCore.QRect(170, 320, 311, 31))
        self.daili_to_who.setObjectName("daili_to_who")
        self.line_2 = QtWidgets.QFrame(self.tab_2)
        self.line_2.setGeometry(QtCore.QRect(110, 275, 371, 5))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.widget4 = QtWidgets.QWidget(self.tab_2)
        self.widget4.setGeometry(QtCore.QRect(110, 360, 371, 25))
        self.widget4.setObjectName("widget4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Button_daili_towho = QtWidgets.QPushButton(self.widget4)
        self.Button_daili_towho.setObjectName("Button_daili_towho")
        self.horizontalLayout_7.addWidget(self.Button_daili_towho)
        self.Button_daili_who = QtWidgets.QPushButton(self.widget4)
        self.Button_daili_who.setObjectName("Button_daili_who")
        self.horizontalLayout_7.addWidget(self.Button_daili_who)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_26 = QtWidgets.QLabel(self.tab_4)
        self.label_26.setGeometry(QtCore.QRect(130, 40, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_28 = QtWidgets.QLabel(self.tab_4)
        self.label_28.setGeometry(QtCore.QRect(130, 245, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.steemp_num = QtWidgets.QLineEdit(self.tab_4)
        self.steemp_num.setGeometry(QtCore.QRect(130, 270, 371, 41))
        self.steemp_num.setObjectName("steemp_num")
        self.label_29 = QtWidgets.QLabel(self.tab_4)
        self.label_29.setGeometry(QtCore.QRect(130, 210, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.Button_scot_sell_all = QtWidgets.QPushButton(self.tab_4)
        self.Button_scot_sell_all.setGeometry(QtCore.QRect(130, 100, 371, 31))
        self.Button_scot_sell_all.setObjectName("Button_scot_sell_all")
        self.Button_steemp = QtWidgets.QPushButton(self.tab_4)
        self.Button_steemp.setGeometry(QtCore.QRect(130, 320, 371, 31))
        self.Button_steemp.setObjectName("Button_steemp")
        self.label_27 = QtWidgets.QLabel(self.tab_4)
        self.label_27.setGeometry(QtCore.QRect(130, 70, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.line_3 = QtWidgets.QFrame(self.tab_4)
        self.line_3.setGeometry(QtCore.QRect(140, 170, 351, 5))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_30 = QtWidgets.QLabel(self.tab_5)
        self.label_30.setGeometry(QtCore.QRect(90, 10, 451, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.create_name = QtWidgets.QLineEdit(self.tab_5)
        self.create_name.setGeometry(QtCore.QRect(90, 240, 321, 31))
        self.create_name.setObjectName("create_name")
        self.Button_rc = QtWidgets.QPushButton(self.tab_5)
        self.Button_rc.setGeometry(QtCore.QRect(90, 110, 191, 31))
        self.Button_rc.setObjectName("Button_rc")
        self.label_31 = QtWidgets.QLabel(self.tab_5)
        self.label_31.setGeometry(QtCore.QRect(90, 60, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.Button_3steem = QtWidgets.QPushButton(self.tab_5)
        self.Button_3steem.setGeometry(QtCore.QRect(300, 110, 191, 31))
        self.Button_3steem.setObjectName("Button_3steem")
        self.label_32 = QtWidgets.QLabel(self.tab_5)
        self.label_32.setGeometry(QtCore.QRect(90, 180, 451, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_5)
        self.label_33.setGeometry(QtCore.QRect(90, 210, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.Button_create_name_chack = QtWidgets.QPushButton(self.tab_5)
        self.Button_create_name_chack.setGeometry(QtCore.QRect(420, 240, 71, 31))
        self.Button_create_name_chack.setObjectName("Button_create_name_chack")
        self.label_34 = QtWidgets.QLabel(self.tab_5)
        self.label_34.setGeometry(QtCore.QRect(90, 280, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.create_mima = QtWidgets.QLineEdit(self.tab_5)
        self.create_mima.setGeometry(QtCore.QRect(90, 310, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.create_mima.setFont(font)
        self.create_mima.setText("")
        self.create_mima.setObjectName("create_mima")
        self.Button_creante_mima = QtWidgets.QPushButton(self.tab_5)
        self.Button_creante_mima.setGeometry(QtCore.QRect(420, 310, 71, 31))
        self.Button_creante_mima.setObjectName("Button_creante_mima")
        self.Button_create = QtWidgets.QPushButton(self.tab_5)
        self.Button_create.setGeometry(QtCore.QRect(90, 350, 401, 31))
        self.Button_create.setObjectName("Button_create")
        self.line_5 = QtWidgets.QFrame(self.tab_5)
        self.line_5.setGeometry(QtCore.QRect(90, 160, 401, 5))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_35 = QtWidgets.QLabel(self.tab_5)
        self.label_35.setGeometry(QtCore.QRect(90, 40, 141, 16))
        self.label_35.setObjectName("label_35")
        self.ticker_num = QtWidgets.QLabel(self.tab_5)
        self.ticker_num.setGeometry(QtCore.QRect(230, 40, 61, 16))
        self.ticker_num.setObjectName("ticker_num")
        self.ticket_load = QtWidgets.QPushButton(self.tab_5)
        self.ticket_load.setGeometry(QtCore.QRect(250, 38, 41, 20))
        self.ticket_load.setObjectName("ticket_load")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_24 = QtWidgets.QLabel(self.tab_6)
        self.label_24.setGeometry(QtCore.QRect(120, 75, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.witness_to = QtWidgets.QLineEdit(self.tab_6)
        self.witness_to.setGeometry(QtCore.QRect(120, 100, 371, 41))
        self.witness_to.setObjectName("witness_to")
        self.label_25 = QtWidgets.QLabel(self.tab_6)
        self.label_25.setGeometry(QtCore.QRect(120, 40, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.Button_witness_yes = QtWidgets.QPushButton(self.tab_6)
        self.Button_witness_yes.setGeometry(QtCore.QRect(120, 160, 371, 31))
        self.Button_witness_yes.setObjectName("Button_witness_yes")
        self.Button_witness_no = QtWidgets.QPushButton(self.tab_6)
        self.Button_witness_no.setGeometry(QtCore.QRect(120, 200, 371, 31))
        self.Button_witness_no.setObjectName("Button_witness_no")
        self.tabWidget.addTab(self.tab_6, "")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(220, 10, 621, 171))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.rcbar = QtWidgets.QProgressBar(self.tab_3)
        self.rcbar.setGeometry(QtCore.QRect(440, 100, 118, 23))
        self.rcbar.setProperty("value", 0)
        self.rcbar.setObjectName("rcbar")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(430, 20, 151, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(170, 20, 151, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(430, 80, 171, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(170, 80, 151, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.voting_bar = QtWidgets.QProgressBar(self.tab_3)
        self.voting_bar.setGeometry(QtCore.QRect(440, 50, 118, 23))
        self.voting_bar.setProperty("value", 0)
        self.voting_bar.setObjectName("voting_bar")
        self.down_bar = QtWidgets.QProgressBar(self.tab_3)
        self.down_bar.setGeometry(QtCore.QRect(180, 100, 118, 23))
        self.down_bar.setProperty("value", 0)
        self.down_bar.setObjectName("down_bar")
        self.Button_load_accwaller = QtWidgets.QPushButton(self.tab_3)
        self.Button_load_accwaller.setGeometry(QtCore.QRect(10, 90, 91, 23))
        self.Button_load_accwaller.setObjectName("Button_load_accwaller")
        self.Button_load_accmess = QtWidgets.QPushButton(self.tab_3)
        self.Button_load_accmess.setGeometry(QtCore.QRect(10, 20, 91, 23))
        self.Button_load_accmess.setObjectName("Button_load_accmess")
        self.sp_mess = QtWidgets.QLabel(self.tab_3)
        self.sp_mess.setGeometry(QtCore.QRect(180, 50, 251, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sp_mess.setFont(font)
        self.sp_mess.setObjectName("sp_mess")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.node_box = QtWidgets.QComboBox(self.tab_9)
        self.node_box.setGeometry(QtCore.QRect(60, 50, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.node_box.setFont(font)
        self.node_box.setObjectName("node_box")
        self.node_box.addItem("")
        self.node_box.addItem("")
        self.node_box.addItem("")
        self.node_box.addItem("")
        self.node_box.addItem("")
        self.node_box.addItem("")
        self.node_box.addItem("")
        self.node_box.addItem("")
        self.node_box.addItem("")
        self.node_box.addItem("")
        self.node_box.addItem("")
        self.label_16 = QtWidgets.QLabel(self.tab_9)
        self.label_16.setGeometry(QtCore.QRect(60, 20, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_3.setGeometry(QtCore.QRect(10, 10, 201, 241))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.widget5 = QtWidgets.QWidget(self.tab_7)
        self.widget5.setGeometry(QtCore.QRect(10, 10, 171, 25))
        self.widget5.setObjectName("widget5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Button_load_acc = QtWidgets.QPushButton(self.widget5)
        self.Button_load_acc.setObjectName("Button_load_acc")
        self.horizontalLayout.addWidget(self.Button_load_acc)
        self.accbox = QtWidgets.QComboBox(self.widget5)
        self.accbox.setObjectName("accbox")
        self.horizontalLayout.addWidget(self.accbox)
        self.widget6 = QtWidgets.QWidget(self.tab_7)
        self.widget6.setGeometry(QtCore.QRect(10, 40, 171, 132))
        self.widget6.setObjectName("widget6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget6)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget6)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.player = QtWidgets.QLineEdit(self.widget6)
        self.player.setObjectName("player")
        self.verticalLayout.addWidget(self.player)
        self.label_2 = QtWidgets.QLabel(self.widget6)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.key = QtWidgets.QLineEdit(self.widget6)
        self.key.setEchoMode(QtWidgets.QLineEdit.Password)
        self.key.setObjectName("key")
        self.verticalLayout.addWidget(self.key)
        self.Button_save = QtWidgets.QPushButton(self.tab_7)
        self.Button_save.setGeometry(QtCore.QRect(10, 180, 71, 21))
        self.Button_save.setObjectName("Button_save")
        self.Button_del = QtWidgets.QPushButton(self.tab_7)
        self.Button_del.setGeometry(QtCore.QRect(110, 180, 71, 21))
        self.Button_del.setObjectName("Button_del")
        self.tabWidget_3.addTab(self.tab_7, "")
        self.moneyWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.moneyWidget.setGeometry(QtCore.QRect(10, 260, 201, 521))
        self.moneyWidget.setObjectName("moneyWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.moneyWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.moneyWidget)
        self.printmessage = QtWidgets.QTextEdit(self.centralwidget)
        self.printmessage.setGeometry(QtCore.QRect(220, 630, 621, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.printmessage.sizePolicy().hasHeightForWidth())
        self.printmessage.setSizePolicy(sizePolicy)
        self.printmessage.setObjectName("printmessage")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(740, 730, 41, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.dial_6 = QtWidgets.QDial(self.centralwidget)
        self.dial_6.setGeometry(QtCore.QRect(760, 650, 50, 64))
        self.dial_6.setProperty("value", 40)
        self.dial_6.setObjectName("dial_6")
        self.dial_5 = QtWidgets.QDial(self.centralwidget)
        self.dial_5.setGeometry(QtCore.QRect(710, 650, 50, 64))
        self.dial_5.setProperty("value", 40)
        self.dial_5.setSliderPosition(40)
        self.dial_5.setObjectName("dial_5")
        self.pbar = QtWidgets.QProgressBar(self.centralwidget)
        self.pbar.setGeometry(QtCore.QRect(290, 720, 401, 23))
        self.pbar.setProperty("value", 0)
        self.pbar.setObjectName("pbar")
        self.par_text = QtWidgets.QLabel(self.centralwidget)
        self.par_text.setGeometry(QtCore.QRect(300, 690, 171, 16))
        self.par_text.setObjectName("par_text")
        steem.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(steem)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 863, 23))
        self.menubar.setObjectName("menubar")
        steem.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(steem)
        self.statusbar.setObjectName("statusbar")
        steem.setStatusBar(self.statusbar)

        self.retranslateUi(steem)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(steem)

    def retranslateUi(self, steem):
        _translate = QtCore.QCoreApplication.translate
        steem.setWindowTitle(_translate("steem", "MainWindow"))
        self.label_8.setText(_translate("steem", "转账Transfer"))
        self.Button_trans.setText(_translate("steem", "OK"))
        self.label_13.setText(_translate("steem", "兑币数量(STEEM or SBD)"))
        self.label_17.setText(_translate("steem", "STEEM-SBD速兑"))
        self.label_18.setText(_translate("steem", "POWER UP & DOWN"))
        self.label_15.setText(_translate("steem", "POWERdown数量Number"))
        self.label_14.setText(_translate("steem", "POWERup数量Number"))
        self.Button_to_steem.setText(_translate("steem", "兑换为STEEM"))
        self.Button_to_sbd.setText(_translate("steem", "兑换成SBD"))
        self.Button_cancer.setText(_translate("steem", "撤销挂单"))
        self.label_19.setText(_translate("steem", "UP和DOWN填一个即可"))
        self.label_9.setText(_translate("steem", "转到to"))
        self.label_10.setText(_translate("steem", "转账币种Token(点击左边币种快速输入)"))
        self.label_11.setText(_translate("steem", "数量Number"))
        self.label_12.setText(_translate("steem", "备忘memo(可留空)"))
        self.Button_power.setText(_translate("steem", "开始up or down"))
        self.Button_cancer_power.setText(_translate("steem", "取消POWERDOWN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("steem", "转账"))
        self.label_3.setText(_translate("steem", "代理给谁？"))
        self.label_21.setText(_translate("steem", "代理SP"))
        self.Button_daili.setText(_translate("steem", "确定"))
        self.label_20.setText(_translate("steem", "数量"))
        self.Button_daili_cancer.setText(_translate("steem", "收回代理"))
        self.label_22.setText(_translate("steem", "代理查询"))
        self.label_23.setText(_translate("steem", "用户:"))
        self.Button_daili_towho.setText(_translate("steem", "你代理给谁？"))
        self.Button_daili_who.setText(_translate("steem", "谁代理给你？"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("steem", "代理"))
        self.label_26.setText(_translate("steem", "SCOT清理"))
        self.label_28.setText(_translate("steem", "提现STEEMP数量："))
        self.label_29.setText(_translate("steem", "STEEMP提现"))
        self.Button_scot_sell_all.setText(_translate("steem", "市价一键出售所有SCOT"))
        self.Button_steemp.setText(_translate("steem", "ok"))
        self.label_27.setText(_translate("steem", "本功能一键市价出售所有SCOT，请确认需要清理再点击"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("steem", "SCOT相关"))
        self.label_30.setText(_translate("steem", "Claim Account Ticket-索取帐户创建票"))
        self.Button_rc.setText(_translate("steem", "使用RC支付"))
        self.label_31.setText(_translate("steem", "您可以在此处索取帐户创建票，然后可以使用该票创建新的Steem帐户。\n"
"可以使用STEEM或RC来支付创建费用，创建票不会过期"))
        self.Button_3steem.setText(_translate("steem", "3 STEEM 支付"))
        self.label_32.setText(_translate("steem", "Create New Account-创建新账号"))
        self.label_33.setText(_translate("steem", "账户名:"))
        self.Button_create_name_chack.setText(_translate("steem", "检查"))
        self.label_34.setText(_translate("steem", "主密码："))
        self.Button_creante_mima.setText(_translate("steem", "生成"))
        self.Button_create.setText(_translate("steem", "创建账户"))
        self.label_35.setText(_translate("steem", "拥有的帐户创建票数量: "))
        self.ticker_num.setText(_translate("steem", "0"))
        self.ticket_load.setText(_translate("steem", "load"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("steem", "创建新账号"))
        self.label_24.setText(_translate("steem", "To"))
        self.label_25.setText(_translate("steem", "见证人投票"))
        self.Button_witness_yes.setText(_translate("steem", "投票"))
        self.Button_witness_no.setText(_translate("steem", "撤票"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("steem", "见证人投票"))
        self.label_5.setText(_translate("steem", "点赞能量Voting Power"))
        self.label_4.setText(_translate("steem", "点赞权重(Vote Weight)"))
        self.label_7.setText(_translate("steem", "资源能量Resource Credits"))
        self.label_6.setText(_translate("steem", "踩人能量Downvote Power"))
        self.Button_load_accwaller.setText(_translate("steem", "读取钱包信息"))
        self.Button_load_accmess.setText(_translate("steem", "读取账号信息"))
        self.sp_mess.setText(_translate("steem", "0 sp   steem power：0 SP"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("steem", "账号信息"))
        self.node_box.setItemText(0, _translate("steem", "https://api.justyy.com"))
        self.node_box.setItemText(1, _translate("steem", "https://cn.steems.top"))
        self.node_box.setItemText(2, _translate("steem", "https://s2.61bts.com"))
        self.node_box.setItemText(3, _translate("steem", "https://api.steemit.com"))
        self.node_box.setItemText(4, _translate("steem", "https://api.steem.bts.tw"))
        self.node_box.setItemText(5, _translate("steem", "https://api.steemitdev.com"))
        self.node_box.setItemText(6, _translate("steem", "https://steemd.privex.io"))
        self.node_box.setItemText(7, _translate("steem", "https://api.steemjiang.com"))
        self.node_box.setItemText(8, _translate("steem", "https://steemd.minnowsupportproject.org"))
        self.node_box.setItemText(9, _translate("steem", "https://steem.61bts.com"))
        self.node_box.setItemText(10, _translate("steem", "https://steem.bts.tw"))
        self.label_16.setText(_translate("steem", "节点(node)"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("steem", "更换节点"))
        self.Button_load_acc.setText(_translate("steem", "账号列表"))
        self.label.setText(_translate("steem", "账号："))
        self.label_2.setText(_translate("steem", "密码（active key）："))
        self.Button_save.setText(_translate("steem", "保存账号"))
        self.Button_del.setText(_translate("steem", "删除账号"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("steem", "steem_wallet"))
        self.moneyWidget.headerItem().setText(0, _translate("steem", "Token"))
        self.moneyWidget.headerItem().setText(1, _translate("steem", "数量"))
        __sortingEnabled = self.moneyWidget.isSortingEnabled()
        self.moneyWidget.setSortingEnabled(False)
        self.moneyWidget.topLevelItem(0).setText(0, _translate("steem", "STEEM"))
        self.moneyWidget.topLevelItem(0).setText(1, _translate("steem", "0"))
        self.moneyWidget.topLevelItem(1).setText(0, _translate("steem", "SBD"))
        self.moneyWidget.topLevelItem(1).setText(1, _translate("steem", "0"))
        self.moneyWidget.setSortingEnabled(__sortingEnabled)
        self.par_text.setText(_translate("steem", "程序运行中，请耐心等待……"))
